name: Fourth Workflow
on: push
env:
  MONGODB_DB_NAME: gha-demo
jobs:
  Build-Job:
    environment: testing
    runs-on: ubuntu-latest
    env:
      MONGODB_CLUSTER_ADDRESS: cluster0.ntrwp.mongodb.net
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      PORT: 8080
    outputs:
      file-name: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Java
        uses: actions/setup-java@v3
        with: 
          java-version: '17'
          distribution: 'temurin'
      - name: Cache the Maven packages to speed up build
        id: cache
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build Project
        if: steps.cache.outputs.cache-hit != 'true'
        run: mvn -B package --file pom.xml -DskipTests
      - name: creating staging folder
        run: mkdir staging && cp target/*.jar staging
      - name: publish Jar file name
        id: publish
        run: find staging/*.jar -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
      - name: echo file name
        run: echo ${{ steps.publish.outputs.script-file }}
      - name: publish the artifact
        uses: actions/upload-artifact@v1
        with:
          name: Package
          path: staging
      - name: Display env 
        run: echo "$MONGODB_DB_NAME $MONGODB_USERNAME"
        
  publish-filename:
    needs: Build-Job
    runs-on: ubuntu-latest
    steps:
      - env:
          env1: ${{ needs.Build-Job.outputs.file-name }}
        run: echo "$env1"
  report:
    needs: [Build-Job, publish-filename]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: | 
          echo "Something went wrong"
          echo "${{ toJSON(github) }}"
  
      
  
