name: Second Workflow
on: push
jobs:
  Build-Job:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Java
        uses: actions/setup-java@v3
        with: 
          java-version: '17'
      - name: Build Project
        run: mvn --batch-mode --update-snapshots verify
            
