name: Second Workflow
on: push
jobs:
  Build-Job:
    runs-on: ubuntu-latest
    outputs:
      file-name: ${{ steps.publish.script-file }}
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Java
        uses: actions/setup-java@v3
        with: 
          java-version: '17'
          distribution: 'temurin'
      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build Project
        run: mvn -B package --file pom.xml -DskipTests
      - name: creating staging folder
        run: mkdir staging && cp target/*.jar staging
      - name: publish Jar file name
        id: publish
        run: find staging/*.jar -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
      - name: publish the artifact
        uses: actions/upload-artifact@v1
        with:
          name: Package
          path: staging
  publish-filename:
    needs: Build-Job
    runs-on: ubuntu-latest
    steps:
      - name: Publish Jar file name
        run: echo "${{ needs.Build-Job.outputs.file-name }}
  
      
  
